version: '3'
services:
  indexer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: indexer:latest
    container_name: indexer
    restart: always
    entrypoint: indexer --accounts GontTwDeBduvbW85oHyC8A7GekuT8X1NkZHDDdUWWvsV,BxTExiVRt9EHe4b47ZDQLDGxee1hPexvkmaDFMLZTDvv --poll 10 --rpc https://rpc.helius.xyz/<API_KEY>
    environment:
      RUST_LOG: info
      INDEXER_DB_CONN_STR: mongodb://service:password@mongo:27017/drift
  mongo:
    image: mongo
    restart: always
    command: --quiet # TODO: mongo container very noisy on start up...
    ports:
      - 27017:27017
    volumes:
     - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: drift